title: Morning OpenStack
description: "Goooood Morning OpenStack : your daily OpenStack cake"
author:
  name: Leslie-Alexandre DENIS
  email: 'leslie@morningopenstack.org'
metadata:
    description: 'MorningOpenStack aime OpenStack'
taxonomies: [tag]

# Owner/author information
owner:
  name:           Leslie-Alexandre DENIS
  email:          'leslie@morningopenstack.org'
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Awesome Dude, Awesome Life
  # Social networking links used in footer. Update and remove as you like.
  twitter:        getgrav
  facebook:       getgrav
  github:         getgrav
  instagram:      getgrav
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/+getgrav

logo: /user/themes/notepad/images/logo.png

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Lumière sur
    url: /featured
  - title: Catégories
    url: /categories
  - title: A Propos
    url: /about

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
